language: node_js
node_js:
  - "7"

cache: yarn

script:
  - yarn test

before_deploy: yarn build

deploy:
  provider: npm
  email:
    secure: ovwM+RPaAjyYW+D4/8ojxGMQAKxmZN3+kskFucdfZJwCGw1hSfv5NPQJQUQ/4y6oTeTxqvvOBWCLa+e3ClLee6kqO5Or5thojkagVJDC7DCRMyD4Zq9GBKS/P7I+lB3B9nzUtFp8Mz14pNljsUuafnwZZ8U6tO/M7rsSaEh1frnTSvRFwL29I4eaDVORGMEhLc3m7Dr6hbuNUZ7LvZXdaI6gXY/CbXEQNtF7ciDI7iW+Wv/8EwwV0vScfysCr2j1AySgXPsLKHhQVz5+6UirVXqPKdbFAQt8HS5Vs6EMZEN87CURpvUCYhDXrZAw1vzApr/e7/NbimNQWd2+80DWa/2evV+B7pHffYqtbPmnlj/Ey3CSrFqopCUS6bRSvo9GajwZjT7KIuzsjEkc/AJ7IoHrXEoN6G2l+Ufw1G1rtVxooIkHZzz7k06FatymvoRaYDg2p/WEMaXUjCHxHE4mDRk6ojVcon0tVwzx7BqU9neMb0wdKdTocwg7J07xRj/X1F/x6Hm8B7MkqMS0BAfYLM4azuP7bjrhoPGLnaBH2X3+X7pETMvYo+pLuY9+j+3/t84qbBClnZvbxf7eMexQSERgevkxllkYYINfl7wf7MKSy6zA/DMnTFlN54OddQDvi1aoSopp2C8OCPBmpZ+hBQH+/W4nooLbuYOsgKNODTY=
  api_key:
    secure: R/JBP3c00OouG6jS7YEFu0pcqfO6ylG8sBLmg1885/o8M8HDCSqM+0elbA196Z4+H4bmbg16TTD5ennTMZqU/I8CIYeN3g5/ysdAyeJihPsqbwiEx8taRURWXrvfaKAnMcGOY0lkyvj8Sxhz9e2nS3PPKOxyEd8cecKcjrL3mp+mqEfrRedb+OtSskkLDPPTUKax7l7qoZOrq9zN/Cdyih/KBPIKrh4hVDvj6fVoognDr2u3eqR1H+L1jTNF/j1Zok4csSsVXGLFvQ4IusUvEv0Dow1qqt4VCRisqr618proscC1UHz1vKtC2jpXDOLlTNcPu4EZQ2of4iNVx2ooVOicO+3iUfLaSq5hgByW+deQTchTZ6pPuoG3YzQQ9ge8lmd0ybqcIVfwn2mYL3EhTYJjyg12Pmi+X4AaK3jD8zk+l9mweDFlu3e2MvzVgtW4irU+B67+AQW8kM0Lu2wwkRET8QUiqj6WW2SbGn3eZ5I/8JoKBzpHK4GT5aPu+a+blLOaY+biE+moASAie0JY+lXVL9va2KhH9Sc/D6AYCrdM7DXN/vD6U6gzHrqC8/VTU209SPXzENUkZzPx3a3ijB6Vb8v/1otLZ4pdLyS+LH9pXT2KCOaZ8u+dg2Ydn9liDa2N8GPZ8Q25Fsts6o1eH9oRNKxJ+eGiHrBPAaZHEh4=
